[tool.pylint.main]

fail-under = 9.0

[tool.pylint."messages control"]

disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "too-few-public-methods",
    "unspecified-encoding",
    "consider-using-with"
]

[tool.coverage.run]

omit = [
    "*test*",
    "*__init__*"
]
